version: '3.3'

services:
  mysql:
    container_name: mysqldb
    image: mysql
    restart: always
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=spotify-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./spotify.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - app-net
    depends_on:
      - mysql
volumes:
  mysql-data:

networks:
  app-net:
    driver: bridge
